### ISSUE TITLE
CLI fails with `ZeroDivisionError` in Emacs

### ISSUE THREAD

**Issue by mhfrantz** [hiptest/hiptest-publisher#16]
With a `hiptest.conf` file like this:
```
token = '<redacted>'
language=javascript
framework=mocha
output_directory = './'
```

Here's what happens when I run it from an Emacs shell window:
```
$ hiptest-publisher -v -c hiptest.conf 
Running Hiptest-publisher 0.9.3 with:
 - __cli_args: #<Set: {:verbose, :config}>
 - __config_args: #<Set: {:token, :language, :framework, :output_directory}>
 - language: "javascript"
 - framework: "mocha"
 - output_directory: "./"
 - overriden_templates: ""
 - test_run_id: ""
 - filter_ids: ""
 - filter_tags: ""
 - tests_only: false
 - actionwords_only: false
 - actionwords_signature: false
 - actionwords_diff: false
 - aw_deleted: false
 - aw_created: false
 - aw_renamed: false
 - aw_signature_changed: false
 - with_folders: false
 - split_scenarios: false
 - leafless_export: false
 - site: "https://hiptest.net"
 - push: ""
 - push_format: "tap"
 - sort: "id"
 - verbose: true
 - config: "hiptest.conf"
 - token: "<redacted>"
URL: https://hiptest.net/publication/<redacted>/project
[x] Fetching data from Hiptest
Unable to open the file, please check that the token is correct
--------------------------------------------------------------------------------
ZeroDivisionError: divided by 0
  /Library/Ruby/Gems/2.0.0/gems/hiptest-publisher-0.9.3/lib/hiptest-publisher/utils.rb:78:in `/'
  /Library/Ruby/Gems/2.0.0/gems/hiptest-publisher-0.9.3/lib/hiptest-publisher/utils.rb:78:in `show_status_message'
  /Library/Ruby/Gems/2.0.0/gems/hiptest-publisher-0.9.3/lib/hiptest-publisher/utils.rb:86:in `with_status_message'
  /Library/Ruby/Gems/2.0.0/gems/hiptest-publisher-0.9.3/lib/hiptest-publisher.rb:72:in `fetch_xml_file'
  /Library/Ruby/Gems/2.0.0/gems/hiptest-publisher-0.9.3/lib/hiptest-publisher.rb:52:in `run'
  /Library/Ruby/Gems/2.0.0/gems/hiptest-publisher-0.9.3/bin/hiptest-publisher:33:in `<top (required)>'
  /usr/bin/hiptest-publisher:23:in `load'
  /usr/bin/hiptest-publisher:23:in `<main>'

--------------------------------------------------------------------------------
```

**Comment by cbliard** [comment]
Released version 0.9.5 of the gem with this fix.
