### ISSUE TITLE
SocketError: Failed to open TCP connection to hiptest.net:443

### ISSUE THREAD

**Issue by tikolakin** [hiptest/hiptest-publisher#52]
Hi, could you please help me to figure out where the configuration is need to be changed in order to allow fetching data from hiptest

the env is the following:
- host machine
- vagrant
- docker

withing vagrant env running the following
```
14:14:25 $ docker run hiptest/hiptest-publisher --token="token" --verbose
[x] Fetching data from Hiptest
Running Hiptest-publisher 1.2.0 with:
 - __cli_args: #<Set: {:token, :verbose}>
 - __config_args: #<Set: {}>
 - language: "ruby"
 - framework: ""
 - output_directory: "."
 - overriden_templates: ""
 - test_run_id: ""
 - test_run_name: ""
 - tests_only: false
 - actionwords_only: false
 - actionwords_signature: false
 - actionwords_diff: false
 - aw_deleted: false
 - aw_created: false
 - aw_renamed: false
 - aw_signature_changed: false
 - aw_definition_changed: false
 - with_folders: false
 - split_scenarios: false
 - leafless_export: false
 - site: "https://hiptest.net"
 - push: ""
 - push_format: "tap"
 - sort: "order"
 - uids: true
 - keep_filenames: false
 - keep_foldernames: false
 - filter_on_scenario_ids: ""
 - filter_on_folder_ids: ""
 - filter_on_scenario_name: ""
 - filter_on_folder_name: ""
 - filter_on_tags: ""
 - filter_on_status: ""
 - check_version: false
 - verbose: true
 - token: "token"
Options have been normalized. Values updated:
 - framework: "rspec"
An error has occured, sorry for the inconvenience.
Try running the command again with --verbose for detailed output
--------------------------------------------------------------------------------
SocketError: Failed to open TCP connection to hiptest.net:443 (getaddrinfo: Try again)
  /usr/local/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect'
  /usr/local/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
  /usr/local/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
  /usr/local/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
  /usr/local/lib/ruby/2.3.0/net/http.rb:878:in `connect'
  /usr/local/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
  /usr/local/lib/ruby/2.3.0/net/http.rb:852:in `start'
  /usr/local/lib/ruby/2.3.0/net/http.rb:584:in `start'
  /usr/local/bundle/gems/hiptest-publisher-1.2.0/lib/hiptest-publisher/client.rb:156:in `send_request'
  /usr/local/bundle/gems/hiptest-publisher-1.2.0/lib/hiptest-publisher/client.rb:143:in `send_get_request'
  /usr/local/bundle/gems/hiptest-publisher-1.2.0/lib/hiptest-publisher/client.rb:60:in `fetch_project_export'
  /usr/local/bundle/gems/hiptest-publisher-1.2.0/lib/hiptest-publisher.rb:86:in `block in fetch_xml_file'
  /usr/local/bundle/gems/hiptest-publisher-1.2.0/lib/hiptest-publisher/formatters/reporter.rb:27:in `with_status_message'
  /usr/local/bundle/gems/hiptest-publisher-1.2.0/lib/hiptest-publisher.rb:85:in `fetch_xml_file'
  /usr/local/bundle/gems/hiptest-publisher-1.2.0/lib/hiptest-publisher.rb:80:in `get_xml_file'
  /usr/local/bundle/gems/hiptest-publisher-1.2.0/lib/hiptest-publisher.rb:58:in `run'
  /usr/local/bundle/gems/hiptest-publisher-1.2.0/bin/hiptest-publisher:38:in `<top (required)>'
  /usr/local/bundle/bin/hiptest-publisher:22:in `load'
  /usr/local/bundle/bin/hiptest-publisher:22:in `<main>'

--------------------------------------------------------------------------------```

**Comment by cbliard** [comment]
Hi,

Are you able to ping both hiptest.net and google.com from your vagrant machine?

**Comment by tikolakin** [comment]
Hi, yep
```
nslookup hiptest.net
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
Name:	hiptest.net
Address: 185.60.151.19
```

**Comment by tikolakin** [comment]
```
vagrant@AllApps:dev:dev:~
16:38:06 $ telnet hiptest.net
Trying 185.60.151.19...
^C

vagrant@AllApps:dev:dev:~
16:38:30 $ docker run --entrypoint "telnet" -it hiptest/hiptest-publisher hiptest.net
telnet: bad address 'hiptest.net'

```

**Comment by tikolakin** [comment]
fixed by https://github.com/moby/moby/issues/866#issuecomment-19218300
so it looks like docker withing vagrant env issue.
Sorry for bothering.

**Comment by cbliard** [comment]
That's interesting. Thanks for having shared your findings with us.
